# Generated by Django 6.0.4 on 2026-04-27 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoSalvo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="certificados/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOVO", "Certificado Novo"),
                            ("VALIDADO", "Já Validado pelo Coordenador"),
                        ],
                        default="NOVO",
                        max_length=20,
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos_salvos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "curso",
                    models.CharField(
                        choices=[
                            ("ontopsicologia", "Ontopsicologia"),
                            ("administracao", "Administração"),
                            ("sistemas_informacao", "Sistemas de Informação"),
                            ("direito", "Direito"),
                            ("pedagogia", "Pedagogia"),
                            ("ciencias_contabeis", "Ciências Contábeis"),
                            ("hotelaria", "Hotelaria"),
                            ("gastronomia", "Gastronomia"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
