# Generated by Django 6.0.4 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificadosalvo",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOVO", "Novo (Aguardando Processamento)"),
                    ("PROCESSADO", "Processado (Enviado à Coordenadoria)"),
                    ("VALIDADO", "Validado (Finalizado)"),
                ],
                default="NOVO",
                max_length=20,
            ),
        ),
    ]
