
services:
  web:
    build: .
    container_name: web_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
      ollama-pull-models:
        condition: service_completed_successfully
    environment:
      - POSTGRES_NAME=indexAC_amf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - OLLAMA_HOST=http://ollama:11434

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=indexAC_amf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]

  ollama-pull-models:
    image: ollama/ollama:latest
    container_name: ollama_model_puller
    entrypoint: ["sh", "-c"]
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    command: >
      "echo 'Aguardando Ollama iniciar...' &&
      while ! ollama list > /dev/null 2>&1; do sleep 2; done &&
      echo 'Baixando Llama 3.1 (Aguarde, este arquivo tem ~5GB)...' &&
      ollama pull llama3.1 &&
      echo 'Baixando MiniCPM-V (Para processamento de imagens)...' &&
      ollama pull minicpm-v &&
      echo 'Todos os modelos foram baixados com sucesso!'"

volumes:
  postgres_data:
  ollama_data:
